# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 15:56
from __future__ import unicode_literals

import adminsortable.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('initial_date', models.DateField()),
                ('final_date', models.DateField()),
            ],
            options={
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entry', adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Entry')),
            ],
            options={
                'ordering': ['order', 'slug'],
            },
        ),
    ]
